version: '2'

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    container_name : 'kafka' 
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONFLUENT_METADATA_SERVICE_URL=http://localhost:8090
    extra_hosts:
      - "kafka:127.0.0.1"
  # debian:
  #   image: 'debian:latest'
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - kafka
  #   command: ["sleep", "infinity"]
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./home_debian:/home_debian
  #   entrypoint: ["/bin/bash", "-c", "apt-get update && apt-get install -y iputils-ping netcat-openbsd python-is-python3 nmap pip && sleep infinity"]

  mysql:
    image: mysql:latest
    networks:
      - app-tier
    environment:
      - MYSQL_ROOT_PASSWORD=fiap
      - MYSQL_DATABASE=db_fiap
      - MYSQL_USER=fiap
      - MYSQL_PASSWORD=fiap
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
